import "@/styles/globals.css";

import type { Metadata } from "next";

import Footer from "@/components/pages/Footer";

type RootPropsType = {
  children: React.ReactNode
}

export default function Root({ children }: RootPropsType) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
        <div id="popups"></div>
      </body>
    </html>
  )
}

export const metadata: Metadata = {
  title: "Hotel Websites",
  description: "Generated by create next app",
}