import "@/css/globals.css";
 
import { cn } from "@/components/shadcn/lib/utils";

import { IBMPlexSans } from "./fonts";
import { OldStandardTT } from "./fonts";

export default function Layout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(
      IBMPlexSans.variable,
      OldStandardTT.variable,
    )}>
      <body className="bg-muted-foreground/5">
        {children}
      </body>
    </html>
  );
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};